// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbLNSTVqVDACnY0zXUcVd122uikt9-bdk',
    appId: '1:1067378977822:web:90c72f8d86aad0964f120f',
    messagingSenderId: '1067378977822',
    projectId: 'mr-ev-tech',
    authDomain: 'mr-ev-tech.firebaseapp.com',
    storageBucket: 'mr-ev-tech.firebasestorage.app',
    measurementId: 'G-VZRR33XR55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTLB9R2Zv9OkxL3rYGgh6kaBTwvsGPXaI',
    appId: '1:1067378977822:android:28a3674da6319d074f120f',
    messagingSenderId: '1067378977822',
    projectId: 'mr-ev-tech',
    storageBucket: 'mr-ev-tech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0hu-8zH18ax0vaMVZ3pfp94x8ITNLyEo',
    appId: '1:1067378977822:ios:b8a79b01733fc6454f120f',
    messagingSenderId: '1067378977822',
    projectId: 'mr-ev-tech',
    storageBucket: 'mr-ev-tech.firebasestorage.app',
    iosBundleId: 'com.example.evTechUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0hu-8zH18ax0vaMVZ3pfp94x8ITNLyEo',
    appId: '1:1067378977822:ios:b8a79b01733fc6454f120f',
    messagingSenderId: '1067378977822',
    projectId: 'mr-ev-tech',
    storageBucket: 'mr-ev-tech.firebasestorage.app',
    iosBundleId: 'com.example.evTechUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbLNSTVqVDACnY0zXUcVd122uikt9-bdk',
    appId: '1:1067378977822:web:d83a2cf6ecce19fb4f120f',
    messagingSenderId: '1067378977822',
    projectId: 'mr-ev-tech',
    authDomain: 'mr-ev-tech.firebaseapp.com',
    storageBucket: 'mr-ev-tech.firebasestorage.app',
    measurementId: 'G-3KF7TBDRLF',
  );
}
